# Generated by Django 5.2.8 on 2025-11-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(choices=[('Math', 'Mathematics'), ('Sci', 'Science'), ('Eng', 'English'), ('Hist', 'History')], max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
